### ISSUE TITLE
프로젝트 유저인터페이스 framework 논의  

### ISSUE THREAD

**Issue by yukmj1123** [yukmj1123/recommendation#1]
프로젝트 유저인터페이스 framework를 어떻게 하면 좋을까요 ? 전 웹을 더 선호해서 웹으로 하는게 더 좋습니다!

**Comment by cyk1105** [comment]
저도 웹 쪽으로 가는 편이 더 좋을 거 같다 생각합니다.

**Comment by jeongminheo** [comment]
저도 어플리케이션보다는 웹을 만져본 경험이 있어서 더 좋을것 같습니다:)

**Comment by bytecell** [comment]
정영섭Prof: 논의가 완료되었다 싶으면, assign 된 사람들 중에 1명 (또는 assignee 들 중에 가장 power(?) 센 사람)이 이슈를 Close 하면 됩니다.

나중에 다시 논의가 필요하게 되면,
그 때 Close 했던 이슈를 reopen 할 수도 있습니다.

**Comment by yukmj1123** [comment]
저는 django 경험이 있어서 다른 framework보다는 django 가 편합니다

**Comment by jeongminheo** [comment]
그럼 diango를 이용해서 프레임워크를 작성하도록 할게요!
