### ISSUE TITLE
입출력 함수에 관한 자료

### ISSUE THREAD

**Issue by jeongminheo** [yukmj1123/recommendation#16]
입출력 함수를 구현하고 있는데 제가 저번학년에 사용한 자료가 도움이 되어서 링크를 추가 합니다.
다음 인구수가 적은 순위로 추천해주는 함수를 구현할때 도움이 될 듯 합니다. 

https://colab.research.google.com/drive/1KygfHA81Uc2BHlGJRozyc0l43BNNzkEh?usp=sharing

https://colab.research.google.com/drive/1J3TCUFWILY2k8OudncgvLSojwYVZxNUB?usp=sharing

**Comment by yukmj1123** [comment]
넵 확인했습니다
