### ISSUE TITLE
구글지도에 좌표 찍히는 부분

### ISSUE THREAD

**Issue by yukmj1123** [yukmj1123/recommendation#18]
구글 지도에 좌표 찍히는 부분 구현한 것 feature_googlepoint 브랜치에 tourmap/templates/registration/map_test1에 있습니다. 데이터 베이스에서 좌표를 불러오는 부분은 아직 구현이 되지않아 정해진 좌표만 띄워주는 부분을 구현한것이라 pr하진 않았습니다.

**Comment by yukmj1123** [comment]
pr했습니다.

**Comment by jeongminheo** [comment]
함수 두번 적혀있어서 하나로 수정하여서 백엔드 작성했습니다
