### ISSUE TITLE
프로젝트의 구체적인 방향 정하기 

### ISSUE THREAD

**Issue by jeongminheo** [yukmj1123/recommendation#3]
프로젝트의 구체적인 방향 정하기 
<관광인구를 분석 후 인구가 적은 여행지 제공>
<관광인구를 분석 후 인구가 적은 여행지를 기준으로 여행루트를 제공>
둘 중에 어떤 방향이 좋을 까요?

**Comment by yukmj1123** [comment]
루트보단 유동 인구가 적은 여행지를 추천해주는 것이  더 좋을 것 같아요 !
루트까지 제공하게 된다면 여행지 사이의 거리도 고민해야해서 많이 복잡해질것같아요

**Comment by cyk1105** [comment]
저도 루트보다는 관광인구를 분석 후 인구가 적은 여행지 까지만 제공하는 방법이 더 깔끔하다 생각해요.
