### ISSUE TITLE
데이터에 관한 문제

### ISSUE THREAD

**Issue by yukmj1123** [yukmj1123/recommendation#6]
데이터를 구한 사이트에서는 '도'를 기준으로 관광인구가 나오는데 시를 기준으로 구할 수 는 없을까요? 
저번 이슈에서 최대한 시 까지 구해보는걸로 했는데 보내주신 사이트는 도를 기준으로 데이터가 나옵니다

**Comment by jeongminheo** [comment]
공공데이터 포털사이트에 시 별로 관광지 데이터와 관광인구 데이터를 발견해서 사용하면 좋을거 같습니다!

**Comment by jeongminheo** [comment]
https://www.data.go.kr/tcs/dss/selectDataSetList.do?dType=FILE&keyword=%EC%A3%BC%EC%9A%94+%EA%B4%80%EA%B4%91%EC%A7%80+%EA%B4%80%EA%B4%91%EA%B0%9D&detailKeyword=&publicDataPk=&recmSe=N&detailText=&relatedKeyword=&commaNotInData=&commaAndData=&commaOrData=&must_not=&tabId=&dataSetCoreTf=&coreDataNm=&sort=_score&relRadio=&orgFullName=&orgFilter=&org=&orgSearch=&currentPage=2&perPage=10&brm=&instt=&svcType=&kwrdArray=&extsn=&coreDataNmArray=&pblonsipScopeCode=

**Comment by yukmj1123** [comment]
네 이 데이터면 적당할거같습니다
