### ISSUE TITLE
프로젝트 평가 기준(성능 검증) 설정이 필요합니다.

### ISSUE THREAD

**Issue by yukmj1123** [yukmj1123/recommendation#8]
프로젝트의 성능 검증을 위한 평가 기준이 필요하다고 생각하는데 기준을 어떻게 정하면 좋을까요 ?
지도 기반 서비스인 만큼 거리를 기준으로 뒀으면 합니다.

**Comment by yukmj1123** [comment]
좋습니다! 거리 기준은 구글맵으로 하고, 추후에 00m이상은 멀다 가깝다 이런 숫자 기준이 필요할거같아요

**Comment by cyk1105** [comment]
사용자 피드백(별점, 후기, 설문조사 등)을 받아서 평가하는 방법도 괜찮을 것 같습니다.
